CREATE DATABASE IF NOT EXISTS school;
USE school;
CREATE TABLE student 
   (STDID VARCHAR(11),
	FIRSTNAME VARCHAR(50), 
	LASTNAME VARCHAR(50), 
	MAJOR CHAR(50), 
	CONSTRAINT PKSTUDENT PRIMARY KEY (STDID)
   ) ;
INSERT INTO student (STDID,FIRSTNAME,LASTNAME,MAJOR) values ('64130500170','SOMCHAI','JAIDEE','IT');
INSERT INTO student (STDID,FIRSTNAME,LASTNAME,MAJOR) values ('64130500280','PETER','CHU', 'CS');
INSERT INTO student (STDID,FIRSTNAME,LASTNAME,MAJOR) values ('64130500460','SOMSRI','RAKREAN', 'DSI');
